version: 2

project_name: bb

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: bb
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/PhilipKram/bitbucket-cli/cmd.version={{.Version}}
      - -X github.com/PhilipKram/bitbucket-cli/cmd.commit={{.ShortCommit}}
      - -X github.com/PhilipKram/bitbucket-cli/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - name: bb
    directory: Formula
    repository:
      owner: PhilipKram
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    homepage: https://github.com/PhilipKram/Bitbucket-CLI
    description: "A command-line tool for Bitbucket Cloud"
    license: MIT
    skip_upload: auto
    test: |
      system "#{bin}/bb", "--version"
    install: |
      bin.install "bb"
